# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'aaronsdemoimages/vslivechicago2018'

steps:
- script: |
    ./scripts/dockerhub-login.sh
    docker build -f demo1/Dockerfile -t $(imageName):demo1 ./demo1
    docker push $(imageName):demo1
  displayName: build and push the demo1 docker image
  env:
    DOCKERHUB_PASSWORD: $(dockerHub.password)
- script: |
    ./scripts/dockerhub-login.sh
    docker build -f demo3/Dockerfile -t $(imageName):demo3 ./demo3
    docker push $(imageName):demo3
  displayName: build and push the demo3 docker image
  env:
    DOCKERHUB_PASSWORD: $(dockerHub.password)
  
