apiVersion: v1
kind: Service
metadata:
  name: vslive2018
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.containerPort }}
  selector:
    app: vslive2018
