version: '3'
services:
  redis:
    image: redis:alpine
    networks:
      - redis-net
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
  all:
    image: aaronsdemoimages/vslivechicago2018:demo3
    networks:
      redis-net:
        aliases: ["redis"]
      default:
    ports:
      - "5000:5000"
    depends_on: [redis]
networks:
  redis-net:
    driver: bridge
